dist:
  trusty

language:
  java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - ./client/node_modules/

before_script:
  -npm install --prefix client/

script:
  - mvn clean test
  - npm run build --prefix client/