dist:
  trusty

language:
  java

jdk:
  - oraclejdk8

node_js:
  - "10"

cache:
  directories:
    - $HOME/.m2
    - ./client/node_modules/
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "facebook-final-project"


before_script:
  - npm install --prefix client/

script:
  - mvn clean test jacoco:report coveralls:report
  - sonar-scanner
  - npm run build --prefix client/