dist:
  trusty

language:
  java

jdk:
  - oraclejdk8

node_js:
  - 10

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "facebook-final-project"
    token:
      secure: ${SONAR_TOKEN}


before_script:
  - npm install --prefix client/
  - node -v

script:
  - mvn clean test jacoco:report coveralls:report
  - sonar-scanner
  - npm run build --prefix client/