spring:
  datasource:
    url: jdbc:mysql://database-1.csriiekhqy3f.us-east-2.rds.amazonaws.com:3306/danbook
    username: admin
    password: passw1234
  jpa:
    hibernate:
      ddl-auto: update

amazonProperties:
  bucketName: fs-8-final
  credentials:
    path: /home/ubuntu/awsKeys/keys-for-s3.properties