amazonProperties:
  bucketName: fs-8-final
  credentials:
    path: src/main/resources/awsKeys/keys-for-s3.properties

spring:
  profiles:
    active: prod
  servlet:
    multipart:
      maxFileSize: 15MB
      maxRequestSize: 15MB
  security:
    jwt-secret:
      ${random.uuid}
    oauth2:
      client:
        registration:
          google:
            client-id: 594844764495-7mu88r8mju2vlbqgasi4fb9f76seeern.apps.googleusercontent.com
            client-secret: A8xUVoRh5M2cDqTTfKK-2zOL

  mail:
    host: smtp.gmail.com
    port: 587
    username: finalfacebook00@gmail.com
    password: cjvbyzofwjrjbzwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
