server:
  port: 8080

amazonProperties:
  endpointUrl: https://s3.us-west-2.amazonaws.com
  bucketName: fs-8

spring:
  profiles:
    active: dev

  security:
      jwt-secret:
        ${random.uuid}

---

spring:
  profiles: prod
  datasource:
    url: jdbc://mysql://localhost:3306/mydb
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: none
