server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  datasource:
    url: jdbc://mysql://localhost:3306/mydb
    username: user
    password:
  jpa:
    hibernate:
      ddl-auto: none
